##
## Author: omargo33@gmail.com
## Date: 2024-03-25
##
##

version: '3'
services:
  mysql:
    image: mysql:5.7.44-oracle
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  mynetwork:
