//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.12 at 05:49:28 p. m. ECT 
//


package com.leon.batch.cliente.estructuras.autorizacion;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.leon.batch.cliente.estructuras.autorizacion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.leon.batch.cliente.estructuras.autorizacion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Authorization }
     * 
     */
    public Authorization createAuthorization() {
        return new Authorization();
    }

    /**
     * Create an instance of {@link Authorization.Mensajes.Mensaje }
     * 
     */
    public Authorization.Mensajes.Mensaje createAuthorizationMensajesMensaje() {
        return new Authorization.Mensajes.Mensaje();
    }

    /**
     * Create an instance of {@link Authorization.Mensajes }
     * 
     */
    public Authorization.Mensajes createAuthorizationMensajes() {
        return new Authorization.Mensajes();
    }

}
